#!/usr/local/bin/zsh -f
umask 002
PACKAGE=org.w3c.css.css

# CLASSPATH=/u/crash/0/w3c/plehegar/www430/validator.zip
CLASSPATH=~/www430:.
export CLASSPATH

# PATH=/u/koala/2/koala/plehegar/JFC/jdk1.2/bin:$PATH
java -Djava.protocol.handler.pkgs="org.w3c.www.protocol|sun.net.www.protocol" $PACKAGE.StyleSheetCom $@
