/* Generated By:JavaCC: Do not edit this line. CssParserConstants.java */
package org.w3c.css.parser.analyzer;

public interface CssParserConstants {

  int EOF = 0;
  int SPC_CHAR = 1;
  int S = 2;
  int CDO = 6;
  int CDC = 7;
  int LBRACE = 8;
  int RBRACE = 9;
  int DASHMATCH = 10;
  int INCLUDES = 11;
  int PREFIXMATCH = 12;
  int SUFFIXMATCH = 13;
  int SUBSTRINGMATCH = 14;
  int TILDE = 15;
  int EQ = 16;
  int PLUS = 17;
  int MINUS = 18;
  int COMMA = 19;
  int SEMICOLON = 20;
  int PRECEDES = 21;
  int DIV = 22;
  int LBRACKET = 23;
  int RBRACKET = 24;
  int ANY = 25;
  int DOT = 26;
  int LPARAN = 27;
  int RPARAN = 28;
  int COLON = 29;
  int AND = 30;
  int MEDIARESTRICTOR = 31;
  int NONASCII = 32;
  int H = 33;
  int UNICODE = 34;
  int ESCAPE = 35;
  int NMSTART = 36;
  int NMCHAR = 37;
  int STRINGCHAR = 38;
  int D = 39;
  int NAME = 40;
  int STRING = 41;
  int IDENT = 42;
  int NUMBER = 43;
  int _URL = 44;
  int URL = 45;
  int PERCENTAGE = 46;
  int LENGTH = 47;
  int EMS = 48;
  int EXS = 49;
  int ANGLE = 50;
  int TIME = 51;
  int FREQ = 52;
  int RESOLUTION = 53;
  int DATE = 54;
  int DIMEN = 55;
  int HASH = 56;
  int IMPORTANT_SYM = 57;
  int IMPORT_SYM = 58;
  int MEDIA_SYM = 59;
  int PAGE_SYM = 60;
  int FONT_FACE_SYM = 61;
  int PREF_SYM = 62;
  int COLOR_PROFILE = 63;
  int CHARSET_SYM = 64;
  int ATTOP = 65;
  int ATRIGHT = 66;
  int ATBOTTOM = 67;
  int ATLEFT = 68;
  int ATCOUNTER = 69;
  int PHONETIC_ALPHABET_SYM = 70;
  int ATKEYWORD = 71;
  int RANGE0 = 72;
  int RANGE1 = 73;
  int RANGE2 = 74;
  int RANGE3 = 75;
  int RANGE4 = 76;
  int RANGE5 = 77;
  int RANGE6 = 78;
  int RANGE = 79;
  int UNI = 80;
  int UNICODERANGE = 81;
  int CLASS = 82;
  int FUNCTION = 83;

  int DEFAULT = 0;
  int IN_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<S>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 5>",
    "\"<!--\"",
    "\"-->\"",
    "\"{\"",
    "\"}\"",
    "\"|=\"",
    "\"~=\"",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"~\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "\";\"",
    "\">\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\".\"",
    "\")\"",
    "\"(\"",
    "\":\"",
    "<AND>",
    "<MEDIARESTRICTOR>",
    "<NONASCII>",
    "<H>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRINGCHAR>",
    "<D>",
    "<NAME>",
    "<STRING>",
    "<IDENT>",
    "<NUMBER>",
    "<_URL>",
    "<URL>",
    "<PERCENTAGE>",
    "<LENGTH>",
    "<EMS>",
    "<EXS>",
    "<ANGLE>",
    "<TIME>",
    "<FREQ>",
    "<RESOLUTION>",
    "<DATE>",
    "<DIMEN>",
    "<HASH>",
    "<IMPORTANT_SYM>",
    "\"@import\"",
    "\"@media\"",
    "\"@page\"",
    "\"@font-face\"",
    "\"@preference\"",
    "\"@color-profile\"",
    "\"@charset\"",
    "\"@top\"",
    "\"@right\"",
    "\"@bottom\"",
    "\"@left\"",
    "\"@counter\"",
    "\"@phonetic-alphabet\"",
    "<ATKEYWORD>",
    "<RANGE0>",
    "<RANGE1>",
    "<RANGE2>",
    "<RANGE3>",
    "<RANGE4>",
    "<RANGE5>",
    "<RANGE6>",
    "<RANGE>",
    "<UNI>",
    "<UNICODERANGE>",
    "<CLASS>",
    "<FUNCTION>",
    "\"::\"",
  };

}
