/* Generated By:JavaCC: Do not edit this line. CssParserConstants.java */
package org.w3c.css.parser.analyzer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CssParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 1;
  /** RegularExpression Id. */
  int H = 2;
  /** RegularExpression Id. */
  int NONASCII = 3;
  /** RegularExpression Id. */
  int UNICODE = 4;
  /** RegularExpression Id. */
  int ESCAPE = 5;
  /** RegularExpression Id. */
  int NMSTART = 6;
  /** RegularExpression Id. */
  int NMCHAR = 7;
  /** RegularExpression Id. */
  int STRING1 = 8;
  /** RegularExpression Id. */
  int STRING2 = 9;
  /** RegularExpression Id. */
  int INVALID1 = 10;
  /** RegularExpression Id. */
  int INVALID2 = 11;
  /** RegularExpression Id. */
  int _IDENT = 12;
  /** RegularExpression Id. */
  int NAME = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int _STRING = 15;
  /** RegularExpression Id. */
  int _INVALID = 16;
  /** RegularExpression Id. */
  int _URL = 17;
  /** RegularExpression Id. */
  int _S = 18;
  /** RegularExpression Id. */
  int _W = 19;
  /** RegularExpression Id. */
  int NL = 20;
  /** RegularExpression Id. */
  int S = 21;
  /** RegularExpression Id. */
  int CDO = 22;
  /** RegularExpression Id. */
  int CDC = 23;
  /** RegularExpression Id. */
  int INCLUDES = 24;
  /** RegularExpression Id. */
  int DASHMATCH = 25;
  /** RegularExpression Id. */
  int LBRACE = 26;
  /** RegularExpression Id. */
  int PLUS = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int GREATER = 29;
  /** RegularExpression Id. */
  int COMMA = 30;
  /** RegularExpression Id. */
  int TILDE = 31;
  /** RegularExpression Id. */
  int AND = 32;
  /** RegularExpression Id. */
  int MEDIARESTRICTOR = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int INVALID = 35;
  /** RegularExpression Id. */
  int IDENT = 36;
  /** RegularExpression Id. */
  int HASHIDENT = 37;
  /** RegularExpression Id. */
  int HASH = 38;
  /** RegularExpression Id. */
  int PROGID = 39;
  /** RegularExpression Id. */
  int RBRACE = 40;
  /** RegularExpression Id. */
  int PREFIXMATCH = 41;
  /** RegularExpression Id. */
  int SUFFIXMATCH = 42;
  /** RegularExpression Id. */
  int SUBSTRINGMATCH = 43;
  /** RegularExpression Id. */
  int EQ = 44;
  /** RegularExpression Id. */
  int SEMICOLON = 45;
  /** RegularExpression Id. */
  int DIV = 46;
  /** RegularExpression Id. */
  int LBRACKET = 47;
  /** RegularExpression Id. */
  int RBRACKET = 48;
  /** RegularExpression Id. */
  int ANY = 49;
  /** RegularExpression Id. */
  int DOT = 50;
  /** RegularExpression Id. */
  int LPARAN = 51;
  /** RegularExpression Id. */
  int RPARAN = 52;
  /** RegularExpression Id. */
  int COLON = 53;
  /** RegularExpression Id. */
  int URL = 54;
  /** RegularExpression Id. */
  int RELFONTLENGTH = 55;
  /** RegularExpression Id. */
  int RELVIEWLENGTH = 56;
  /** RegularExpression Id. */
  int ABSOLUTLENGTH = 57;
  /** RegularExpression Id. */
  int FLEX = 58;
  /** RegularExpression Id. */
  int ANGLE = 59;
  /** RegularExpression Id. */
  int SPL = 60;
  /** RegularExpression Id. */
  int ST = 61;
  /** RegularExpression Id. */
  int TIME = 62;
  /** RegularExpression Id. */
  int FREQ = 63;
  /** RegularExpression Id. */
  int RESOLUTION = 64;
  /** RegularExpression Id. */
  int DIMEN_9 = 65;
  /** RegularExpression Id. */
  int DIMEN = 66;
  /** RegularExpression Id. */
  int PERCENTAGE = 67;
  /** RegularExpression Id. */
  int NUMBER = 68;
  /** RegularExpression Id. */
  int IMPORTANT_SYM = 69;
  /** RegularExpression Id. */
  int IMPORTANT_NOT = 70;
  /** RegularExpression Id. */
  int PSEUDOELEMENT_SYM = 71;
  /** RegularExpression Id. */
  int CHARSET_SYM = 72;
  /** RegularExpression Id. */
  int IMPORT_SYM = 73;
  /** RegularExpression Id. */
  int NAMESPACE_SYM = 74;
  /** RegularExpression Id. */
  int MEDIA_SYM = 75;
  /** RegularExpression Id. */
  int PAGE_SYM = 76;
  /** RegularExpression Id. */
  int FONT_FACE_SYM = 77;
  /** RegularExpression Id. */
  int KEYFRAMES_SYM = 78;
  /** RegularExpression Id. */
  int PREF_SYM = 79;
  /** RegularExpression Id. */
  int COLOR_PROFILE = 80;
  /** RegularExpression Id. */
  int ATTOP = 81;
  /** RegularExpression Id. */
  int ATRIGHT = 82;
  /** RegularExpression Id. */
  int ATBOTTOM = 83;
  /** RegularExpression Id. */
  int ATLEFT = 84;
  /** RegularExpression Id. */
  int A_COUNTER = 85;
  /** RegularExpression Id. */
  int COUNTER_STYLE_SYM = 86;
  /** RegularExpression Id. */
  int PHONETIC_ALPHABET_SYM = 87;
  /** RegularExpression Id. */
  int ATKEYWORD = 88;
  /** RegularExpression Id. */
  int RANGE0 = 89;
  /** RegularExpression Id. */
  int RANGE1 = 90;
  /** RegularExpression Id. */
  int RANGE2 = 91;
  /** RegularExpression Id. */
  int RANGE3 = 92;
  /** RegularExpression Id. */
  int RANGE4 = 93;
  /** RegularExpression Id. */
  int RANGE5 = 94;
  /** RegularExpression Id. */
  int RANGE6 = 95;
  /** RegularExpression Id. */
  int RANGE = 96;
  /** RegularExpression Id. */
  int UNI = 97;
  /** RegularExpression Id. */
  int UNICODERANGE = 98;
  /** RegularExpression Id. */
  int CLASS = 99;
  /** RegularExpression Id. */
  int FUNCTIONLANG = 100;
  /** RegularExpression Id. */
  int FUNCTIONNOT = 101;
  /** RegularExpression Id. */
  int FUNCTIONCALC = 102;
  /** RegularExpression Id. */
  int FUNCTIONATTR = 103;
  /** RegularExpression Id. */
  int FUNCTION = 104;
  /** RegularExpression Id. */
  int HTMLSTARTTAG = 105;
  /** RegularExpression Id. */
  int HTMLENDTAG = 106;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "<H>",
    "<NONASCII>",
    "<UNICODE>",
    "<ESCAPE>",
    "<NMSTART>",
    "<NMCHAR>",
    "<STRING1>",
    "<STRING2>",
    "<INVALID1>",
    "<INVALID2>",
    "<_IDENT>",
    "<NAME>",
    "<NUM>",
    "<_STRING>",
    "<_INVALID>",
    "<_URL>",
    "<_S>",
    "<_W>",
    "<NL>",
    "<S>",
    "\"<!--\"",
    "\"-->\"",
    "<INCLUDES>",
    "\"|=\"",
    "<LBRACE>",
    "<PLUS>",
    "\"-\"",
    "<GREATER>",
    "<COMMA>",
    "<TILDE>",
    "\"and\"",
    "<MEDIARESTRICTOR>",
    "<STRING>",
    "<INVALID>",
    "<IDENT>",
    "<HASHIDENT>",
    "<HASH>",
    "<PROGID>",
    "\"}\"",
    "\"^=\"",
    "\"$=\"",
    "\"*=\"",
    "\"=\"",
    "\";\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\".\"",
    "\")\"",
    "\"(\"",
    "\":\"",
    "<URL>",
    "<RELFONTLENGTH>",
    "<RELVIEWLENGTH>",
    "<ABSOLUTLENGTH>",
    "<FLEX>",
    "<ANGLE>",
    "<SPL>",
    "<ST>",
    "<TIME>",
    "<FREQ>",
    "<RESOLUTION>",
    "<DIMEN_9>",
    "<DIMEN>",
    "<PERCENTAGE>",
    "<NUMBER>",
    "<IMPORTANT_SYM>",
    "<IMPORTANT_NOT>",
    "\"::\"",
    "\"@charset\"",
    "\"@import\"",
    "\"@namespace\"",
    "\"@media\"",
    "\"@page\"",
    "\"@font-face\"",
    "\"@keyframes\"",
    "\"@preference\"",
    "\"@color-profile\"",
    "\"@top\"",
    "\"@right\"",
    "\"@bottom\"",
    "\"@left\"",
    "\"@counter\"",
    "\"@counter-style\"",
    "\"@phonetic-alphabet\"",
    "<ATKEYWORD>",
    "<RANGE0>",
    "<RANGE1>",
    "<RANGE2>",
    "<RANGE3>",
    "<RANGE4>",
    "<RANGE5>",
    "<RANGE6>",
    "<RANGE>",
    "<UNI>",
    "<UNICODERANGE>",
    "<CLASS>",
    "\"lang(\"",
    "\":not(\"",
    "\"calc(\"",
    "\"attr(\"",
    "<FUNCTION>",
    "<HTMLSTARTTAG>",
    "<HTMLENDTAG>",
    "<token of kind 107>",
    "\"|\"",
    "\"%\"",
  };

}
